### ISSUE TITLE
appel de tir() et oxygène qui demande un angle.

### ISSUE THREAD

**Issue by Popiette** [Popiette/ISN#1]
On va avoir un soucis là, car chaque atome doit pouvoir tirer tout seul comme un grand, de manière à ce qu'on puisse simplement appeller une fonction tir() sans avoir à se soucier de si c'est un atome d'hydrogène, de carbone, d'oxygène... Or l'oxygène demande un angle.

**Comment by DantCold** [comment]
résolu kek
